<?php

$modversion['name'] = _MI_XSURVEY_NAME;
$modversion['version'] = 0.1;
$modversion['description'] = _MI_XSURVEY_DESC;
$modversion['author'] = 'Ikke<br>http://www.eikke.com';
$modversion['credits'] = 'jcleeland<br>http://phpsurveyor.sourceforge.net';
//$modversion['help'] = "admin/instructions.html";
$modversion['license'] = 'QPL see LICENSE.QPL';
$modversion['official'] = 0;
$modversion['image'] = 'images/xsurvey_slogo.png';
$modversion['dirname'] = 'xsurvey';

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = 'sql/mysql.sql';
//$modversion['sqlfile']['postgresql'] = "sql/pgsql.sql";

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = 'xsurvey_surveys';
//$modversion['tables'][1] = "xsurvey_conditions";
//$modversion['tables'][2] = "xsurvey_groups";
//$modversion['tables'][3] = "xsurvey_labels";
//$modversion['tables'][4] = "xsurvey_labelsets";
$modversion['tables'][5] = 'xsurvey_questions';
//$modversion['tables'][6] = "xsurvey_answers";

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = 'admin/index.php';
//$modversion['adminmenu'] = "admin/menu.php";

// Menu
$modversion['hasMain'] = 1;

$modversion['onUninstall'] = 'OnUninstall.php';

//Could we use a loop in here to add all template files? Or is that 'illegal' in Xoops? :-D
//Problem is: new template files could be added from time to time
$modversion['templates'][1]['file'] = 'xsurvey_survey_onebyone.html';
$modversion['templates'][1]['description'] = '';
$modversion['templates'][2]['file'] = 'xsurvey_question_yesno.html';
$modversion['templates'][2]['description'] = '';
